import React, { useEffect, useMemo, useRef, useState } from 'react';
import { Activity, ArrowUpRight, BarChart3, BellRing, ChevronRight, Cpu, Database, Download, Gauge, Layers3, Menu, Network, Radar, Radio, Sparkles, X } from 'lucide-react';
import { motion } from 'motion/react';
import { gsap } from 'gsap';
import KpiCardGrid from './components/KpiCardGrid';
import MineNodeGrid from './components/MineNodeGrid';
import RealTimePredictor from './components/RealTimePredictor';
import HistoricalAnalytics from './components/HistoricalAnalytics';
import LiveReplaySimulator from './components/LiveReplaySimulator';
import BatchCsvScorer from './components/BatchCsvScorer';
import { Button } from './components/ui/button';

const navItems = [
  { id: 'predictor', path: '/monitor', label: 'Live monitor', icon: Radar, kicker: '01 / SIGNAL ROOM', title: 'Live field picture', description: 'The ground is speaking in real time. Watch every node, threshold, and risk score converge into one operational view.' },
  { id: 'historical', path: '/analytics', label: 'Analytics', icon: BarChart3, kicker: '02 / PATTERN LAB', title: 'Find the drift before the event', description: 'Move through historical telemetry, model confidence, and deformation patterns to understand what is changing beneath the panel.' },
  { id: 'replay', path: '/replay', label: 'Event replay', icon: Activity, kicker: '03 / TIME MACHINE', title: 'Replay the signal', description: 'Scrub through recorded sensor moments and inspect how a warning becomes a decision.' },
  { id: 'batch', path: '/batch', label: 'Batch scoring', icon: Database, kicker: '04 / DATA DESK', title: 'Score a whole shift', description: 'Upload and score a telemetry batch against the latest calibrated subsidence model.' },
];
const pipeline = [{ label: 'Sense', detail: 'ESP32 nodes', icon: Radio, color: 'lime' }, { label: 'Transmit', detail: 'LoRa mesh', icon: Network, color: 'cyan' }, { label: 'Understand', detail: 'Edge + AI', icon: Cpu, color: 'violet' }, { label: 'Act', detail: 'Early warning', icon: BellRing, color: 'orange' }];

function resolvePage() { return navItems.find(item => window.location.pathname === item.path) || navItems[0]; }
function go(path) { window.history.pushState({}, '', path); window.dispatchEvent(new PopStateEvent('popstate')); }

function PageTransition({ page, children }) {
  useEffect(() => {
    const ctx = gsap.context(() => {
      const tl = gsap.timeline({ defaults: { ease: 'power3.out' } });
      tl.set('.route-curtain', { clipPath: 'inset(0 0 0 0)' })
        .to('.route-curtain-line', { scaleY: 1, duration: .28, ease: 'power2.inOut' })
        .to('.route-curtain-line', { scaleY: 0, transformOrigin: 'top', duration: .36 }, '+=.06')
        .to('.route-curtain', { clipPath: 'inset(0 0 0 100%)', duration: .52, ease: 'power4.inOut' }, '-=.08')
        .from('.route-kicker', { y: 18, opacity: 0, duration: .38 }, '-=.22')
        .from('.route-title', { y: 28, opacity: 0, duration: .48 }, '-=.28')
        .from('.route-description, .route-content', { y: 20, opacity: 0, duration: .42, stagger: .06 }, '-=.24');
    });
    return () => ctx.revert();
  }, [page.id]);
  return <div className="route-frame" key={page.id}><div className="route-curtain"><div className="route-curtain-line" /></div><div className="route-head"><div><div className="route-kicker section-label">{page.kicker}</div><h1 className="route-title">{page.title}</h1><p className="route-description">{page.description}</p></div><div className="route-index">{page.id === 'predictor' ? 'LIVE / 01' : page.id === 'historical' ? 'DATA / 02' : page.id === 'replay' ? 'TIME / 03' : 'FILE / 04'}</div></div><div className="route-content">{children}</div></div>;
}

function MeshPreview() {
  const points = [[15,32],[27,61],[40,38],[52,69],[62,24],[75,51],[88,29],[82,78],[34,84],[67,88]];
  const links = [[0,1],[0,2],[1,3],[2,3],[2,4],[3,5],[4,5],[4,6],[5,7],[3,8],[7,9],[5,9]];
  return <div className="mesh-visual"><motion.div className="mesh-pulse" animate={{ scale: [.82,1.18,.82], opacity: [.2,.48,.2] }} transition={{ duration: 3.2, repeat: Infinity, ease: 'easeInOut' }} /><div className="mesh-orbit orbit-one" /><div className="mesh-orbit orbit-two" /><svg viewBox="0 0 100 100"><defs><linearGradient id="meshLine" x1="0" x2="1"><stop offset="0" stopColor="#b7ff4a" stopOpacity=".18" /><stop offset="1" stopColor="#46e7f2" stopOpacity=".6" /></linearGradient><filter id="nodeGlow"><feGaussianBlur stdDeviation="1.8" result="blur" /><feMerge><feMergeNode in="blur" /><feMergeNode in="SourceGraphic" /></feMerge></filter></defs>{links.map(([a,b]) => <line key={`${a}-${b}`} x1={points[a][0]} y1={points[a][1]} x2={points[b][0]} y2={points[b][1]} stroke="url(#meshLine)" strokeWidth=".45" />)}<circle cx="51" cy="53" r="11" fill="rgba(183,255,74,.08)" stroke="#b7ff4a" strokeOpacity=".55" strokeWidth=".3" /><path d="M51 44v18M42 53h18" stroke="#b7ff4a" strokeWidth=".45" />{points.map(([x,y],i) => <motion.circle key={`${x}-${y}`} cx={x} cy={y} r={i%4!==2?1.8:1.4} fill={i%4!==2?'#b7ff4a':'#ffab5c'} animate={{ opacity: [.5,1,.5], r: [1.4,2.1,1.4] }} transition={{ duration: 1.8+(i%4)*.25, repeat: Infinity, delay: i*.09 }} />)}</svg><div className="mesh-label mesh-label-top"><span className="status-dot" /> LIVE NODE GRID</div><div className="mesh-label mesh-label-bottom">MINE PANEL A / 07:42:18 IST</div><div className="mesh-readout"><span>RSSI</span><strong>-62 dBm</strong><i /><span>PACKETS</span><strong>99.98%</strong></div></div>;
}
function InteractiveHero({ children }) { const root=useRef(null); const copy=useRef(null); const mesh=useRef(null); const spotlight=useRef(null); const scanline=useRef(null); useEffect(()=>{const ctx=gsap.context(()=>{const moveX=gsap.quickTo([copy.current,mesh.current,spotlight.current],'x',{duration:.55,ease:'power3.out'}); const moveY=gsap.quickTo([copy.current,mesh.current,spotlight.current],'y',{duration:.55,ease:'power3.out'}); const intro=gsap.timeline({repeat:-1,yoyo:true,defaults:{ease:'sine.inOut'}}); intro.to(mesh.current,{rotate:1.5,duration:3}).to(spotlight.current,{scale:1.18,opacity:.5,duration:2.5},'<').to(scanline.current,{y:'110%',opacity:.8,duration:4.5,ease:'none'},0); const onMove=e=>{const r=root.current.getBoundingClientRect();const x=((e.clientX-r.left)/r.width-.5)*22;const y=((e.clientY-r.top)/r.height-.5)*16;moveX(copy.current===null?0:x);moveY(copy.current===null?0:y);gsap.to(mesh.current,{x:-x*.7,y:-y*.7,duration:.7,ease:'power3.out',overwrite:true});gsap.to(spotlight.current,{x:x*1.4,y:y*1.4,duration:.9,ease:'power2.out',overwrite:true})}; const onLeave=()=>{gsap.to([copy.current,mesh.current,spotlight.current],{x:0,y:0,rotate:0,duration:.8,ease:'elastic.out(1,.65)',overwrite:true})}; root.current.addEventListener('pointermove',onMove);root.current.addEventListener('pointerleave',onLeave);return()=>{root.current?.removeEventListener('pointermove',onMove);root.current?.removeEventListener('pointerleave',onLeave)}},root);return()=>ctx.revert()},[]); return <section ref={root} className="hero-section"><div ref={spotlight} className="hero-spotlight"/><div ref={copy} className="hero-copy">{children[0]}</div><div ref={mesh} className="hero-mesh-layer">{children[1]}</div><div ref={scanline} className="hero-scanline"/></section>; }

function Sidebar({ page, mobileNav, setMobileNav }) { return <aside className={`sidebar ${mobileNav?'sidebar-open':''}`}><div className="brand-lockup"><div className="brand-mark"><span/><span/><span/></div><div><strong>carbonex</strong><small>ground intelligence</small></div></div><button className="mobile-close" onClick={()=>setMobileNav(false)} aria-label="Close navigation"><X size={20}/></button><div className="sidebar-kicker">Workspace</div><nav className="side-nav">{navItems.map(({id,path,label,icon:Icon})=><button key={id} className={page.id===id?'nav-item active':'nav-item'} onClick={()=>{go(path);setMobileNav(false)}}><Icon size={17}/><span>{label}</span>{page.id===id&&<motion.span layoutId="active-nav" className="nav-active-pill"/>}<ChevronRight size={15} className="nav-arrow"/></button>)}</nav><div className="sidebar-spacer"/><div className="system-card"><div className="system-card-header"><span className="status-dot"/> SYSTEM NOMINAL</div><div className="system-card-value">99.98<span>%</span></div><div className="system-card-note">mesh availability / last 24h</div><div className="mini-bar"><i/></div></div><div className="sidebar-footer"><span>CARBONEX / 0.9.4</span><span className="env-pill">EDGE + CLOUD</span></div></aside>; }

function DashboardPage({ page, nodesSummary, selectedNode, setSelectedNode, activeRisk, liveNodes }) { return <PageTransition page={page}><div><div className="route-console"><span><Layers3 size={15}/> {liveNodes} nodes reporting</span><span><Gauge size={15}/> peak risk {activeRisk.toFixed(1)}</span></div><KpiCardGrid nodesSummary={nodesSummary} activeNode={selectedNode}/><MineNodeGrid nodesSummary={nodesSummary} selectedNode={selectedNode} onSelectNode={setSelectedNode}/><div className="route-module"><RealTimePredictor activeNode={selectedNode}/></div></div></PageTransition>; }
function AnalyticsPage({ page, selectedNode }) { return <PageTransition page={page}><HistoricalAnalytics activeNode={selectedNode}/></PageTransition>; }
function ReplayPage({ page, selectedNode }) { return <PageTransition page={page}><LiveReplaySimulator activeNode={selectedNode}/></PageTransition>; }
function BatchPage({ page }) { return <PageTransition page={page}><BatchCsvScorer/></PageTransition>; }

export default function App() {
  const [page,setPage]=useState(resolvePage); const [nodes,setNodes]=useState(['Node01']); const [selectedNode,setSelectedNode]=useState('Node01'); const [nodesSummary,setNodesSummary]=useState([]); const [mobileNav,setMobileNav]=useState(false);
  useEffect(()=>{const onPop=()=>setPage(resolvePage());window.addEventListener('popstate',onPop);return()=>window.removeEventListener('popstate',onPop)},[]);
  useEffect(()=>{async function init(){try{const [a,b]=await Promise.all([fetch('/api/status'),fetch('/api/nodes-summary')]);if(a.ok){const d=await a.json();if(d.nodes?.length){setNodes(d.nodes);setSelectedNode(c=>d.nodes.includes(c)?c:d.nodes[0])}}if(b.ok)setNodesSummary(await b.json())}catch(e){console.error('Error initializing CarboNex data:',e)}}init();const i=setInterval(init,15000);return()=>clearInterval(i)},[]);
  const activeRisk=useMemo(()=>nodesSummary.length?Math.max(...nodesSummary.map(n=>n.risk_score||0)):18.4,[nodesSummary]); const liveNodes=nodesSummary.length||nodes.length;
  return <div className="app-shell"><Sidebar page={page} mobileNav={mobileNav} setMobileNav={setMobileNav}/>{mobileNav&&<button className="nav-scrim" onClick={()=>setMobileNav(false)} aria-label="Close navigation"/>}<main className="main-content"><header className="topbar"><button className="mobile-menu" onClick={()=>setMobileNav(true)} aria-label="Open navigation"><Menu size={22}/></button><div className="breadcrumb"><span>CARBONEX</span><ChevronRight size={14}/><strong>{page.label.toUpperCase()}</strong></div><div className="topbar-actions"><span className="sync-status"><span className="status-dot"/> synced 12s ago</span><button className="icon-button" title="Download report"><Download size={17}/></button><div className="avatar">AK</div></div></header>{page.id==='predictor'&&<><InteractiveHero><div><div className="eyebrow"><span className="eyebrow-line"/> MINE PANEL A / RANIGANJ COALFIELD</div><h1>See the ground<br/><em>before it moves.</em></h1><p className="hero-description">Carbonex turns distributed sensing into an early-warning advantage. From the first millidegree of tilt to a field-ready alert.</p><div className="hero-actions"><Button className="primary-button" onClick={()=>document.querySelector('.route-frame')?.scrollIntoView({behavior:'smooth'})}>Open live workspace <ArrowUpRight size={16}/></Button><Button variant="ghost" className="text-button" onClick={()=>go('/analytics')}>Explore analytics <span>↗</span></Button></div><div className="hero-proof"><div><strong>24 / 7</strong><span>continuous sensing</span></div><div><strong>4.2 km</strong><span>mesh coverage</span></div><div><strong>6 min</strong><span>early signal window</span></div></div></div><MeshPreview/></InteractiveHero><section className="pipeline-strip"><div className="pipeline-intro"><span className="section-label">THE SIGNAL PATH</span><strong>One system.<br/>Every layer connected.</strong></div>{pipeline.map(({label,detail,icon:Icon,color},i)=><React.Fragment key={label}><div className={`pipeline-step ${color}`}><div className="pipeline-icon"><Icon size={17}/></div><div><span>0{i+1}</span><strong>{label}</strong><small>{detail}</small></div></div>{i<pipeline.length-1&&<div className="pipeline-connector"/>}</React.Fragment>)}<div className="pipeline-end"><Sparkles size={16}/><span>AI READY</span></div></section><DashboardPage page={page} nodesSummary={nodesSummary} selectedNode={selectedNode} setSelectedNode={setSelectedNode} activeRisk={activeRisk} liveNodes={liveNodes}/></>}{page.id==='historical'&&<AnalyticsPage page={page} selectedNode={selectedNode}/>} {page.id==='replay'&&<ReplayPage page={page} selectedNode={selectedNode}/>} {page.id==='batch'&&<BatchPage page={page}/>}<footer className="app-footer"><div><strong>carbonex</strong> / ground intelligence platform</div><div>Built for safer extraction <span>•</span> Smart India Hackathon 2025</div></footer></main></div>;
}
